// Regenerates ai_lab_dev_diary_context.snapshot.ts from ai_lab_dev_diary_context.md.
//
// Why this exists: Supabase's Edge Function deploy bundles the *module graph* the function's
// entrypoint actually imports (an ESZip built by walking `import`s), not every sibling file that
// happens to sit in the same directory. A non-imported file like the canonical .md is not
// guaranteed to be included unless it is explicitly declared as a Function's `static_files` in
// supabase/config.toml (Supabase CLI >=2.7.0) -- this repo declares none for x-test-post, and
// adding one would itself be a new production deploy-config change. A plain `import` of a
// generated .ts constant has no such gap: it is unconditionally part of the module graph, the
// same way every other _shared/brand/*.ts import already is, with no new deploy configuration.
//
// So: ai_lab_dev_diary_context.md stays the canonical, human/ChatGPT-editable source. This script
// embeds its exact current bytes into ai_lab_dev_diary_context.snapshot.ts as a plain string
// constant, which the runtime loader (ai_lab_dev_diary_context.ts) imports directly -- no file
// read, therefore no "missing/unreadable at runtime" failure mode for the primary path.
//
// Run after editing the Markdown, then commit both files together:
//   node --experimental-strip-types supabase/functions/_shared/brand/generate_ai_lab_dev_diary_snapshot.ts
//
// ai_lab_dev_diary_context_test.ts's parity test fails if the committed snapshot ever diverges
// from the Markdown (e.g. someone edited one but not the other, or forgot to rerun this script).

import { readFile, writeFile } from "node:fs/promises";

const SOURCE_URL = new URL("./ai_lab_dev_diary_context.md", import.meta.url);
const SNAPSHOT_URL = new URL("./ai_lab_dev_diary_context.snapshot.ts", import.meta.url);

export function renderSnapshotModule(markdown: string): string {
  return `// AUTO-GENERATED by generate_ai_lab_dev_diary_snapshot.ts from ai_lab_dev_diary_context.md.
// Do not hand-edit: edit that Markdown file, then rerun the generator (see its header comment)
// and commit both files together. ai_lab_dev_diary_context_test.ts fails if these diverge.

// A plain JSON-stringified string literal, not a template literal: safe against any Markdown
// content (backticks, \${...}) without needing its own escaping logic.
export const AI_LAB_DEV_DIARY_MARKDOWN_SNAPSHOT: string = ${JSON.stringify(markdown)};
`;
}

async function main() {
  const markdown = await readFile(SOURCE_URL, "utf8");
  await writeFile(SNAPSHOT_URL, renderSnapshotModule(markdown), "utf8");
  console.log(`Wrote ${SNAPSHOT_URL.pathname} from ${SOURCE_URL.pathname} (${markdown.length} chars).`);
}

// Only run when executed directly (not when imported by the parity test).
if (import.meta.url === `file://${process.argv[1]}` || import.meta.main) {
  await main();
}
