import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, radius, spacing, typography } from '@/constants/theme';
import { useAuth } from '@/providers/auth-provider';

export function AuthScreen() {
  const { backendAvailable, error: authError, signIn } = useAuth();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function handleSignIn() { if (!email.trim() || !password) { setMessage('メールアドレスとパスワードを入力してください。'); return; } setBusy(true); setMessage(null); const result = await signIn(email.trim(), password); setBusy(false); if (!result.ok) setMessage(result.message ?? 'ログインできませんでした。'); }
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.root}><View style={styles.card}><Text style={typography.title}>Social Operations</Text><Text style={styles.subtitle}>AI運用担当者とSNS発信を整える</Text>{!backendAvailable ? <View style={styles.notice}><Text style={styles.noticeText}>{authError ?? 'Supabase環境変数を設定してください。'}（現在はサインインできません）</Text></View> : null}<Text style={styles.label}>メールアドレス</Text><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" onChangeText={setEmail} placeholder="you@example.com" style={styles.input} value={email} /><Text style={styles.label}>パスワード</Text><TextInput autoCapitalize="none" autoComplete="password" onChangeText={setPassword} placeholder="パスワード" secureTextEntry style={styles.input} value={password} /><Pressable accessibilityRole="button" disabled={busy || !backendAvailable} onPress={() => void handleSignIn()} style={({ pressed }) => [styles.button, (pressed || busy || !backendAvailable) && styles.disabled]}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>ログイン</Text>}</Pressable>{message ? <Text style={styles.error}>{message}</Text> : null}<Text style={styles.caption}>Phase 2では認証境界のみ実装しています。新規登録・OAuth接続は次フェーズです。</Text></View></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background, padding: spacing.md }, card: { width: '100%', maxWidth: 440, gap: spacing.sm, backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.lg, padding: spacing.lg }, subtitle: { color: colors.muted, ...typography.body, marginBottom: spacing.md }, label: { color: colors.ink, fontSize: 13, fontWeight: '700', marginTop: spacing.sm }, input: { borderColor: colors.border, borderRadius: radius.sm, borderWidth: 1, color: colors.ink, padding: 12 }, button: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: radius.sm, marginTop: spacing.md, minHeight: 46, justifyContent: 'center' }, buttonText: { color: '#fff', fontWeight: '800' }, disabled: { opacity: 0.45 }, error: { color: colors.danger, fontSize: 13 }, caption: { color: colors.muted, ...typography.caption, marginTop: spacing.md }, notice: { backgroundColor: colors.warningSoft, borderRadius: radius.sm, padding: spacing.sm }, noticeText: { color: colors.warning, fontSize: 13 } });
