import type { PropsWithChildren } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, radius, spacing, typography } from '@/constants/theme';

export function Screen({ children }: PropsWithChildren) { return <View style={styles.screen}>{children}</View>; }
export function Card({ children, style }: PropsWithChildren<{ style?: object }>) { return <View style={[styles.card, style]}>{children}</View>; }
export function SectionTitle({ children, detail }: PropsWithChildren<{ detail?: string }>) { return <View style={styles.sectionTitle}><Text style={styles.heading}>{children}</Text>{detail ? <Text style={styles.muted}>{detail}</Text> : null}</View>; }
export function Pill({ children, tone = 'neutral' }: PropsWithChildren<{ tone?: 'neutral' | 'success' | 'warning' | 'danger' }>) { const palette = tone === 'success' ? [colors.successSoft, colors.success] : tone === 'warning' ? [colors.warningSoft, colors.warning] : tone === 'danger' ? [colors.dangerSoft, colors.danger] : [colors.primarySoft, colors.primary]; return <View style={[styles.pill, { backgroundColor: palette[0] }]}><Text style={[styles.pillText, { color: palette[1] }]}>{children}</Text></View>; }
export function ActionButton({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.button, pressed && styles.buttonPressed]}><Text style={styles.buttonText}>{label}</Text></Pressable>; }
export function EmptyState({ title, detail }: { title: string; detail: string }) { return <Card style={styles.empty}><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.muted}>{detail}</Text></Card>; }
export const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background, padding: spacing.md, gap: spacing.md }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.md, gap: spacing.sm }, heading: typography.heading, sectionTitle: { gap: 4 }, muted: { color: colors.muted, ...typography.caption }, pill: { alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: spacing.sm, paddingVertical: 4 }, pillText: { fontSize: 12, fontWeight: '700' }, button: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: radius.sm, paddingVertical: 12, paddingHorizontal: spacing.md }, buttonPressed: { opacity: 0.75 }, buttonText: { color: '#FFFFFF', fontWeight: '700' }, empty: { alignItems: 'center', paddingVertical: spacing.xl }, emptyTitle: { color: colors.ink, fontSize: 16, fontWeight: '700' } });
