-- S2: read-only catalog read-back after the chain is applied. No user rows, no secrets.
-- The owner role is reported as OWNER so a local proof apply and production compare directly.
-- check.py compares this JSON with expected_readback.json (generated by `run.sh proof`).
with rel as (
  select c.oid, c.relowner from pg_class c where c.oid = to_regclass('public.social_mobile_content_settings')
),
fns as (
  select p.* from pg_proc p
  where p.pronamespace = 'public'::regnamespace and p.proname like 'social\_mobile\_content\_settings\_%'
),
roles as (
  select r.rolname from pg_roles r where r.rolname in ('anon', 'authenticated', 'service_role')
),
privs(p) as (
  values ('SELECT'), ('INSERT'), ('UPDATE'), ('DELETE'), ('TRUNCATE'), ('REFERENCES'), ('TRIGGER'), ('MAINTAIN')
)
select jsonb_build_object(
  'history', (select coalesce(jsonb_agg(jsonb_build_object('version', m.version, 'name', m.name) order by m.version), '[]'::jsonb)
      from supabase_migrations.schema_migrations m where m.version in ('20260922045046', '20261003120000')),
  'table', (select jsonb_build_object(
        'owner_is_current_user', pg_get_userbyid(c.relowner) = current_user,
        'relkind', c.relkind, 'persistence', c.relpersistence,
        'rls', c.relrowsecurity, 'force_rls', c.relforcerowsecurity, 'partition', c.relispartition)
      from pg_class c join rel using (oid)),
  'columns', (select jsonb_agg(format('%s:%s:%s:%s', a.attname, format_type(a.atttypid, a.atttypmod), a.attnotnull,
        coalesce(pg_get_expr(d.adbin, d.adrelid), '')) order by a.attname collate "C")
      from pg_attribute a join rel on a.attrelid = rel.oid
      left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
      where a.attnum > 0 and not a.attisdropped),
  'constraints', (select jsonb_agg(format('%s:%s:%s:%s', con.conname, con.contype, con.convalidated, pg_get_constraintdef(con.oid))
        order by con.conname collate "C")
      from pg_constraint con join rel on con.conrelid = rel.oid),
  'indexes', (select jsonb_agg(pg_get_indexdef(i.indexrelid) order by pg_get_indexdef(i.indexrelid) collate "C")
      from pg_index i join rel on i.indrelid = rel.oid),
  'triggers', (select jsonb_agg(pg_get_triggerdef(t.oid) order by t.tgname collate "C")
      from pg_trigger t join rel on t.tgrelid = rel.oid where not t.tgisinternal),
  'policies', (select jsonb_agg(jsonb_build_object('name', p.polname, 'cmd', p.polcmd, 'permissive', p.polpermissive,
        'roles', (select jsonb_agg(coalesce(r.rolname, 'PUBLIC') order by r.rolname) from unnest(p.polroles) x(oid)
                  left join pg_roles r on r.oid = x.oid),
        'using', pg_get_expr(p.polqual, p.polrelid), 'check', pg_get_expr(p.polwithcheck, p.polrelid))
        order by p.polname collate "C")
      from pg_policy p join rel on p.polrelid = rel.oid),
  'table_acl', (select jsonb_agg(x.v order by x.v collate "C") from (
      select format('%s=%s', case when acl.grantee = rel.relowner then 'OWNER' else coalesce(r.rolname, 'PUBLIC') end,
        acl.privilege_type) as v
      from rel cross join lateral aclexplode(coalesce((select relacl from pg_class where oid = rel.oid), acldefault('r', rel.relowner))) acl
      left join pg_roles r on r.oid = acl.grantee) x),
  'column_acl_count', (select count(*) from pg_attribute a join rel on a.attrelid = rel.oid where a.attacl is not null),
  'effective_table_privileges', (select jsonb_object_agg(roles.rolname,
        (select coalesce(jsonb_agg(privs.p order by privs.p), '[]'::jsonb) from privs
         where has_table_privilege(roles.rolname, 'public.social_mobile_content_settings', privs.p)))
      from roles),
  'public_table_privileges', (select coalesce(jsonb_agg(acl.privilege_type order by acl.privilege_type), '[]'::jsonb)
      from rel cross join lateral aclexplode(coalesce((select relacl from pg_class where oid = rel.oid), acldefault('r', rel.relowner))) acl
      where acl.grantee = 0),
  'functions', (select jsonb_agg(jsonb_build_object(
        'signature', fns.proname || '(' || pg_get_function_identity_arguments(fns.oid) || ')',
        'owner_is_table_owner', fns.proowner = (select relowner from rel),
        'kind', fns.prokind, 'secdef', fns.prosecdef, 'volatility', fns.provolatile, 'parallel', fns.proparallel,
        'config', fns.proconfig, 'language', (select lanname from pg_language where oid = fns.prolang),
        'returns', pg_get_function_result(fns.oid), 'src_md5', md5(fns.prosrc),
        'acl', (select jsonb_agg(x.v order by x.v collate "C") from (
                  select format('%s=%s', case when acl.grantee = fns.proowner then 'OWNER' else coalesce(r.rolname, 'PUBLIC') end,
                    acl.privilege_type) as v
                  from aclexplode(coalesce(fns.proacl, acldefault('f', fns.proowner))) acl left join pg_roles r on r.oid = acl.grantee) x),
        'execute', (select jsonb_agg(roles.rolname order by roles.rolname) from roles
                    where has_function_privilege(roles.rolname, fns.oid, 'EXECUTE')))
        order by fns.proname collate "C")
      from fns)
) as readback;
