import { pathToFileURL } from "node:url";
import {
  buildMorningGreetingGeneratedPath,
  MORNING_GREETING_GENERATED_PREFIX,
  resolveJstDate,
} from "./morning-greeting-image.ts";
import { YUME_CANONICAL_REFERENCE_BUCKET } from "../supabase/functions/x-test-post/yume_reference_logic.ts";

// Early warning for the morning greeting image. The image is pre-generated by morning-greeting-image.yml
// on GitHub's scheduler, which since 2026-09-20 has created runs hours late, so the image kept landing
// after the 06:30-07:00 JST post and the post failed with MORNING_GREETING_IMAGE_NOT_FOUND for days
// without anyone noticing. This check runs shortly before the posting window and fails visibly when the
// day's image is not there.
//
// This check runs on the same unreliable scheduler, so it must not trust its own start time: an image
// that exists *now* may still have arrived after the post. It therefore compares the stored object's
// created_at with the earliest posting-window start for that JST date, so a delayed check run reaches the
// same verdict an on-time run would have. It only reads (posting_windows, Storage object list): it never
// generates an image, never writes Storage or the database, and never touches X.

export const MORNING_GREETING_IMAGE_CHECK_LIST_PAGE_SIZE = 100;
const MAX_LIST_PAGES = 20;
const SUPPORTED_WINDOW_TIMEZONE = "Asia/Tokyo";
const JST_OFFSET = "+09:00";

export class MorningGreetingImageCheckError extends Error {
  readonly dateJst: string | null;
  readonly imageCreatedAt: string | null;
  readonly deadline: string | null;

  constructor(
    code: string,
    details: { dateJst?: string | null; imageCreatedAt?: string | null; deadline?: string | null } = {},
  ) {
    super(code);
    this.name = "MorningGreetingImageCheckError";
    this.dateJst = details.dateJst ?? null;
    this.imageCreatedAt = details.imageCreatedAt ?? null;
    this.deadline = details.deadline ?? null;
  }
}

export type MorningGreetingImageCheckResult =
  | { success: true; result: "disabled"; date_jst: string }
  | { success: true; result: "on_time"; date_jst: string; image_created_at: string; deadline: string };

export type MorningGreetingWindowResult =
  | { enabled: false }
  | { enabled: true; deadline: Date };

function baseUrl(supabaseUrl: string): string {
  return supabaseUrl.trim().replace(/\/$/u, "");
}

function serviceRoleHeaders(serviceRoleKey: string): Record<string, string> {
  return { apikey: serviceRoleKey, Authorization: `Bearer ${serviceRoleKey}` };
}

function parseWindowStartTime(value: unknown): { hours: string; minutes: string; seconds: string } | null {
  if (typeof value !== "string") return null;
  const match = /^(\d{2}):(\d{2})(?::(\d{2})(?:\.\d+)?)?$/u.exec(value);
  if (!match) return null;
  const [, hours, minutes, seconds = "00"] = match;
  if (Number(hours) > 23 || Number(minutes) > 59 || Number(seconds) > 59) return null;
  return { hours, minutes, seconds };
}

// Reads the same posting_windows rows the admin toggle writes (see checkMorningGreetingEnabled in
// morning-greeting-image.ts) plus their start_time. The deadline is the earliest window start for the
// date: the image has to exist before the first moment the post can run.
export async function readMorningGreetingWindow({
  supabaseUrl,
  serviceRoleKey,
  dateJst,
  fetchImpl = fetch,
}: {
  supabaseUrl: string;
  serviceRoleKey: string;
  dateJst: string;
  fetchImpl?: typeof fetch;
}): Promise<MorningGreetingWindowResult> {
  const params = new URLSearchParams({
    select: "is_active,start_time,timezone",
    brand_id: "eq.kabumori",
    post_type: "eq.morning_greeting",
  });

  let response: Response;
  try {
    response = await fetchImpl(`${baseUrl(supabaseUrl)}/rest/v1/posting_windows?${params}`, {
      headers: serviceRoleHeaders(serviceRoleKey),
    });
  } catch {
    throw new MorningGreetingImageCheckError("MORNING_GREETING_WINDOW_READ_FAILED:network", { dateJst });
  }
  if (!response.ok) {
    throw new MorningGreetingImageCheckError(`MORNING_GREETING_WINDOW_READ_FAILED:${response.status}`, { dateJst });
  }

  let rows: unknown;
  try {
    rows = await response.json();
  } catch {
    throw new MorningGreetingImageCheckError("MORNING_GREETING_WINDOW_RESPONSE_MALFORMED", { dateJst });
  }
  if (!Array.isArray(rows) || rows.length === 0) {
    throw new MorningGreetingImageCheckError("MORNING_GREETING_WINDOW_NOT_FOUND", { dateJst });
  }

  const parsed = rows.map((row) => {
    const record = (typeof row === "object" && row !== null ? row : {}) as Record<string, unknown>;
    return { isActive: record.is_active, startTime: parseWindowStartTime(record.start_time), timezone: record.timezone };
  });
  if (parsed.some((row) => typeof row.isActive !== "boolean" || row.startTime === null)) {
    throw new MorningGreetingImageCheckError("MORNING_GREETING_WINDOW_RESPONSE_MALFORMED", { dateJst });
  }
  // Same rule as checkMorningGreetingEnabled: never invent a resolution when rows disagree.
  if (new Set(parsed.map((row) => row.isActive)).size > 1) {
    throw new MorningGreetingImageCheckError("MORNING_GREETING_WINDOW_AMBIGUOUS", { dateJst });
  }
  if (parsed[0].isActive === false) return { enabled: false };
  // Asia/Tokyo has no DST, so a fixed +09:00 offset is exact; any other zone is refused, not guessed.
  if (parsed.some((row) => row.timezone !== SUPPORTED_WINDOW_TIMEZONE)) {
    throw new MorningGreetingImageCheckError("MORNING_GREETING_WINDOW_TIMEZONE_UNSUPPORTED", { dateJst });
  }

  const earliest = Math.min(...parsed.map(({ startTime }) =>
    new Date(`${dateJst}T${startTime!.hours}:${startTime!.minutes}:${startTime!.seconds}${JST_OFFSET}`).getTime()
  ));
  if (!Number.isFinite(earliest)) {
    throw new MorningGreetingImageCheckError("MORNING_GREETING_WINDOW_RESPONSE_MALFORMED", { dateJst });
  }
  return { enabled: true, deadline: new Date(earliest) };
}

// Uses Storage's object list endpoint (the one supabase-js list() calls) because it returns each
// object's created_at. `search` narrows the listing to the date's file name; matching is still done on
// the exact name, and the listing is paged so a server that ignored `search` could not hide the object
// behind the first page. Any unexpected shape fails the check instead of passing it.
export async function findMorningGreetingImageCreatedAt({
  supabaseUrl,
  serviceRoleKey,
  dateJst,
  fetchImpl = fetch,
}: {
  supabaseUrl: string;
  serviceRoleKey: string;
  dateJst: string;
  fetchImpl?: typeof fetch;
}): Promise<Date | null> {
  const objectPath = buildMorningGreetingGeneratedPath(dateJst);
  const fileName = objectPath.slice(`${MORNING_GREETING_GENERATED_PREFIX}/`.length);
  const listUrl = `${baseUrl(supabaseUrl)}/storage/v1/object/list/${encodeURIComponent(YUME_CANONICAL_REFERENCE_BUCKET)}`;

  for (let page = 0; page < MAX_LIST_PAGES; page += 1) {
    let response: Response;
    try {
      response = await fetchImpl(listUrl, {
        method: "POST",
        headers: { ...serviceRoleHeaders(serviceRoleKey), "Content-Type": "application/json" },
        body: JSON.stringify({
          prefix: MORNING_GREETING_GENERATED_PREFIX,
          search: fileName,
          limit: MORNING_GREETING_IMAGE_CHECK_LIST_PAGE_SIZE,
          offset: page * MORNING_GREETING_IMAGE_CHECK_LIST_PAGE_SIZE,
          sortBy: { column: "name", order: "asc" },
        }),
      });
    } catch {
      throw new MorningGreetingImageCheckError("MORNING_GREETING_IMAGE_CHECK_READ_FAILED:network", { dateJst });
    }
    if (!response.ok) {
      throw new MorningGreetingImageCheckError(`MORNING_GREETING_IMAGE_CHECK_READ_FAILED:${response.status}`, {
        dateJst,
      });
    }

    let entries: unknown;
    try {
      entries = await response.json();
    } catch {
      throw new MorningGreetingImageCheckError("MORNING_GREETING_IMAGE_CHECK_RESPONSE_MALFORMED", { dateJst });
    }
    if (!Array.isArray(entries)) {
      throw new MorningGreetingImageCheckError("MORNING_GREETING_IMAGE_CHECK_RESPONSE_MALFORMED", { dateJst });
    }

    const match = entries.find((entry) =>
      typeof entry === "object" && entry !== null && (entry as { name?: unknown }).name === fileName
    ) as { created_at?: unknown } | undefined;
    if (match) {
      const createdAt = typeof match.created_at === "string" ? new Date(match.created_at) : null;
      if (!createdAt || !Number.isFinite(createdAt.getTime())) {
        throw new MorningGreetingImageCheckError("MORNING_GREETING_IMAGE_CHECK_RESPONSE_MALFORMED", { dateJst });
      }
      return createdAt;
    }
    if (entries.length < MORNING_GREETING_IMAGE_CHECK_LIST_PAGE_SIZE) return null;
  }
  throw new MorningGreetingImageCheckError("MORNING_GREETING_IMAGE_CHECK_LIST_TOO_LARGE", { dateJst });
}

export async function runMorningGreetingImageCheck(args: {
  supabaseUrl: string;
  serviceRoleKey: string;
  date?: string;
  now?: Date;
  fetchImpl?: typeof fetch;
}): Promise<MorningGreetingImageCheckResult> {
  let dateJst: string;
  try {
    dateJst = args.date?.trim() || resolveJstDate(args.now);
    buildMorningGreetingGeneratedPath(dateJst);
  } catch {
    throw new MorningGreetingImageCheckError("MORNING_GREETING_DATE_INVALID");
  }

  const reader = {
    supabaseUrl: args.supabaseUrl,
    serviceRoleKey: args.serviceRoleKey,
    dateJst,
    fetchImpl: args.fetchImpl,
  };
  const postingWindow = await readMorningGreetingWindow(reader);
  if (!postingWindow.enabled) return { success: true, result: "disabled", date_jst: dateJst };

  const deadline = postingWindow.deadline.toISOString();
  const createdAt = await findMorningGreetingImageCreatedAt(reader);
  if (!createdAt) {
    throw new MorningGreetingImageCheckError("MORNING_GREETING_IMAGE_MISSING", { dateJst, deadline });
  }
  const imageCreatedAt = createdAt.toISOString();
  if (createdAt.getTime() >= postingWindow.deadline.getTime()) {
    throw new MorningGreetingImageCheckError("MORNING_GREETING_IMAGE_LATE", { dateJst, imageCreatedAt, deadline });
  }
  return { success: true, result: "on_time", date_jst: dateJst, image_created_at: imageCreatedAt, deadline };
}

// Fixed, non-sensitive text only: the code, the JST date and timestamps. Never a response body, a URL or
// an exception message, so nothing derived from the Supabase URL or key can reach the log.
export function formatMorningGreetingImageCheckFailure(error: unknown): { annotation: string; json: string } {
  const checkError = error instanceof MorningGreetingImageCheckError ? error : null;
  const code = checkError?.message ?? "MORNING_GREETING_IMAGE_CHECK_UNEXPECTED";
  const dateJst = checkError?.dateJst ?? null;
  const hint = code === "MORNING_GREETING_IMAGE_MISSING" && dateJst
    ? ` Manual fallback: gh workflow run morning-greeting-image.yml -f target_date=${dateJst}`
    : code === "MORNING_GREETING_IMAGE_LATE"
    ? " The image was stored after the posting window opened, so that day's scheduled post likely failed."
    : "";
  return {
    annotation: `::error title=Morning greeting image check::${code}${dateJst ? ` (date ${dateJst})` : ""}.${hint}`,
    json: JSON.stringify({
      success: false,
      error: code,
      date_jst: dateJst,
      image_created_at: checkError?.imageCreatedAt ?? null,
      deadline: checkError?.deadline ?? null,
    }),
  };
}

function requiredEnvironment(name: string): string {
  const value = process.env[name]?.trim() ?? "";
  if (!value) throw new MorningGreetingImageCheckError(`MORNING_GREETING_ENV_MISSING:${name}`);
  return value;
}

async function main(): Promise<void> {
  try {
    const result = await runMorningGreetingImageCheck({
      supabaseUrl: requiredEnvironment("SUPABASE_URL"),
      serviceRoleKey: requiredEnvironment("SUPABASE_SERVICE_ROLE_KEY"),
      date: process.env.MORNING_GREETING_DATE,
    });
    console.log(JSON.stringify(result));
  } catch (error) {
    const failure = formatMorningGreetingImageCheckFailure(error);
    console.log(failure.annotation);
    console.error(failure.json);
    process.exitCode = 1;
  }
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) await main();
