import { Link } from 'expo-router';
import { ScrollView, Text, View } from 'react-native';
import { mockRepository } from '@/data/mock-repository';
import { colors, typography } from '@/constants/theme';
import { ActionButton, Card, Pill, Screen, SectionTitle, styles } from '@/components/ui';
import { BrandPostPreview } from '@/features/brand-preview/brand-post-preview';
import { useActiveAccount } from '@/providers/active-account-provider';
import { useDataStatus } from '@/providers/data-provider';
import { SignOutButton } from '@/components/sign-out-button';

export default function HomeScreen() {
  const { activeAccount } = useActiveAccount(); const { status, reason, snapshot } = useDataStatus(); const workspace = snapshot?.workspace ?? mockRepository.getWorkspace(); const planned = (snapshot?.plannedPosts ?? mockRepository.getPlannedPosts()).filter((post) => post.accountId === activeAccount?.id); const failed = (snapshot?.history ?? mockRepository.getHistory()).filter((post) => post.accountId === activeAccount?.id && post.status === 'failed').length;
  return <Screen><ScrollView contentContainerStyle={{ gap: 16 }} showsVerticalScrollIndicator={false}><View style={{ gap: 6 }}><Text style={typography.caption}>{workspace.name}</Text><Text style={typography.title}>おはようございます</Text><Text style={{ color: colors.muted, ...typography.body }}>AI運用担当者と、今日の発信を整えましょう。</Text></View>{status !== 'mock_preview' ? <Card style={{ backgroundColor: status === 'ready' ? colors.successSoft : colors.warningSoft, borderColor: status === 'ready' ? '#BBF7D0' : '#FDE68A' }}><Text style={{ color: status === 'ready' ? colors.success : colors.warning, fontWeight: '800' }}>{status === 'ready' ? '接続済みデータ' : status === 'loading' ? 'データ読み込み中' : 'ローカルプレビュー'}</Text>{reason ? <Text style={{ color: colors.muted }}>{reason}</Text> : null}</Card> : null}<Card><SectionTitle detail="選択中のアカウント">運用アカウント</SectionTitle>{activeAccount ? <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}><View style={{ width: 42, height: 42, borderRadius: 21, backgroundColor: activeAccount.profile.avatarColor }} /><View style={{ flex: 1 }}><Text style={{ fontWeight: '700', color: colors.ink }}>{activeAccount.profile.displayName}</Text><Text style={{ color: colors.muted }}>{activeAccount.profile.handle}</Text></View><Pill tone="success">接続済み</Pill></View> : <Text style={styles.muted}>アカウントを選択してください。</Text>}<Link href="/accounts" asChild><ActionButton label="アカウントを切り替える" onPress={() => {}} /></Link></Card><BrandPostPreview brandId={activeAccount?.brandId} workspaceName={workspace.name} handle={activeAccount?.profile.handle} /><View style={{ flexDirection: 'row', gap: 10 }}><Card style={{ flex: 1 }}><Text style={styles.muted}>今日の予定</Text><Text style={{ color: colors.ink, fontSize: 28, fontWeight: '800' }}>{planned.length}件</Text></Card><Card style={{ flex: 1 }}><Text style={styles.muted}>要確認</Text><Text style={{ color: failed ? colors.danger : colors.ink, fontSize: 28, fontWeight: '800' }}>{failed}件</Text></Card></View><Card style={{ backgroundColor: colors.primarySoft, borderColor: '#C7D2FE' }}><Text style={{ color: colors.primary, fontWeight: '800' }}>AI運用担当者からの提案</Text><Text style={{ color: colors.ink, ...typography.body }}>今週は投稿の冒頭を短くすると、読みやすさが上がりそうです。</Text><Link href="/(tabs)/consult" asChild><ActionButton label="相談内容を見る" onPress={() => {}} /></Link></Card><SignOutButton /></ScrollView></Screen>;
}
